// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSCR.Extension
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidVSCRPackageString = "8abfea05-824c-43d0-9466-e084f4890f44";
        public static Guid guidVSCRPackage = new Guid(guidVSCRPackageString);

        public const string guidVSCRPackageCmdSetString = "c37ba89f-ac4a-4bb3-b247-62b960fc88d0";
        public static Guid guidVSCRPackageCmdSet = new Guid(guidVSCRPackageCmdSetString);

        public const string guidMessageBubbleIconString = "39f59862-d9d4-4f7b-804d-8917086239e3";
        public static Guid guidMessageBubbleIcon = new Guid(guidMessageBubbleIconString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ChatToolWindowCommandId = 0x0100;
        public const int mainIconId = 0x0001;
    }
}